# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8067ec73021b5d3a94cc4bcdd14f25471eb3e1bf7ad2ab2a5f00398f385f093d3cfd2214a7e5f0d03b139282ecc323b3daec0fb773e785a265784ea75335266f

test:
  secret_key_base: 209a75e89d88bc85497396e3165e90ae85661db2254d3acd519ce49f9574354bd6edf59c95347bb9ab01d71cdd75ce93a0574ef8a634ff2d25cbaaad2bc61965

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
